"""empty message

Revision ID: 93101cc687a3
Revises: 2514188eaa6b
Create Date: 2025-09-27 20:31:31.744959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93101cc687a3'
down_revision = '2514188eaa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
